# Generated by Django 3.0.2 on 2020-03-25 10:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('dish', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('JPN', '和食'), ('LOCAL', '郷土料理'), ('SUSHI', '寿司'), ('RAMEN', 'ラーメン類'), ('CURRY', 'カレー'), ('FA', 'ファミレス・ファストフード'), ('MEAT', '焼肉・ステーキ等の肉関連'), ('BAR', '居酒屋・バー'), ('CHN', '中華'), ('WES', '洋食'), ('ITA', 'イタリアン'), ('FRA', 'フレンチ'), ('ASIA', 'アジア・エスニック'), ('CAFE', 'カフェ'), ('SWEETS', 'スイーツ'), ('OTHER', 'その他')], max_length=20)),
                ('expense', models.IntegerField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
