# Generated by Django 3.0.2 on 2020-03-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
    ]
