# Generated by Django 3.0.2 on 2020-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv0', '0002_auto_20200325_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Uploaded image'),
        ),
    ]
