# Generated by Django 3.0.2 on 2020-04-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv0', '0003_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editable',
            field=models.BooleanField(default=False),
        ),
    ]
